### ISSUE TITLE
Simpler Install or better instructions

### ISSUE THREAD

**Issue by duh-Capt** [Onred/pwalinks#1] opened 2024-11-20 23:35 UTC
Hello,
I came across your Firefox extension while attempting to create a PWA for Google Messages in Firefox.  The PWA works fine but clicking on links in messages causes the window to be taken over by the linked website.  I'm trying to prevent that and have it open in the default browser window.

Your extension looks to do exactly what I'm looking for except I can't figure out how to install it.  I'm not a programmer, so is it possible for you to give a simpler install method like it is all done within the extension itself?  Or could you give better step by step instructions for how to install your code in Windows? 

Many thanks!

**Comment by Onred** [comment] 2024-11-21 10:20
Thanks for reaching out and showing interest in the extension. I originally developed this for myself to use on Linux, but I have now included a Windows install script in the git files and updated the README to be a bit more clear. Simply clone the repository or download the files directly and run the `windows_installer.bat` script as an administrator.

Big note: I wasn't happy with the original name of the addon, so I have submitted the same addon with the new, updated name. You might have to wait a day or two for it to get approved, but once it is, it will be available at the link in the README.

Ideally I would have the installer run as part of the add extension process, but since this is my first Firefox extension, I lack the experience to do that at this time.

Closing this issue for now. Please open a new issue if there is a bug in the windows installer or if the extension doesn't work as intended (make sure to use the new extension once it's approved).

**Closed as completed** 2024-11-21 10:20 UTC
